#!/usr/bin/env bash
docker build -t clj-helloworld .
#docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app clj-helloworld lein repl
docker run -it --rm -p 12345:12345 clj-helloworld lein repl :headless :host 0.0.0.0 :port 12345
